
public interface ArtInterface {
    
    public void draw(); // WE CAN CREATE ONE MORE TYPE OF ART THAT IS STATUES AND WE CAN USE THAT FUNCTION FOR DIFFERENT PROCESSES FOR EACH TYPE OF ART ( WE NEED STATUES CLASS )
    
}
